# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Support Auto"
client_id = "081c74d6e732614490fc34887c5632a4"
application_url = "https://automerce.vercel.app"
embedded = true

[access_scopes]
scopes = "read_orders,write_orders,read_customers,read_content"

[auth]
redirect_urls = [
  "https://automerce.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

[[webhooks.subscriptions]]
topics = ["orders/create", "orders/updated", "orders/paid", "orders/fulfilled", "orders/cancelled"]
uri = "https://automerce.vercel.app/api/webhooks/orders"

[[webhooks.subscriptions]]
topics = ["refunds/create"]
uri = "https://automerce.vercel.app/api/webhooks/refunds"

[[webhooks.subscriptions]]
topics = ["customers/data-request", "customers/redact", "shop/redact"]
uri = "https://automerce.vercel.app/api/webhooks/gdpr"

[[webhooks.subscriptions]]
topics = ["app/uninstalled", "app/scopes_update"]
uri = "https://automerce.vercel.app/api/webhooks/gdpr"

[build]
automatically_update_urls_on_deploy = true
